### PR TITLE
Adding Connect four browser game!

### PR DESCRIPTION
**Pull request by countchrisdo**
It's a simple game made in HTML, CSS and Javascript but I think people can learn from it

### CODE REVIEW

**Comment by hanshulll** [comment]
@countchrisdo 
**can you explain about what is connect four**

**Comment by countchrisdo** [comment]
> @countchrisdo **can you explain about what is connect four**

Inside my project folder there is a README to explain the game but in short, you try and get 4 of your pieces in a row while blocking the other player. 

Here is a gif: https://upload.wikimedia.org/wikipedia/commons/a/ad/Connect_Four.gif

**Comment by hanshulll** [comment]
@countchrisdo 
I got it but actually, your project folder is not opening.

**Comment by countchrisdo** [comment]
I should have fixed the problem, can you take a look?

**Comment by hanshulll** [comment]
@countchrisdo 
**cool just wait let me merge it in the meantime you can give me a follow and star the repo if it helped you**

**Review by hanshulll — APPROVED** [review]

**Comment by hanshulll** [comment]
@countchrisdo 
**Your PR has been successfully merged Thank you so much for your valuable contribution. Do check other repo for more contributions Keep hacking**

**Pull request merged**
