### PR TITLE
Created the hotel site template using HTML-CSS

### PR DESCRIPTION
**Pull request by salmangada**
Hii, I created the hotel site template using HTML-CSS by referring the below image. I hope you find it helpful.
There are lots of .md files  comitted by me please fix it as I dont know where they came from.
Capture
m

### CODE REVIEW

**Comment by hanshulll** [comment]
@salmangada 
**is this repo showing in the participating repo on hactoberfest page ?**

**Comment by salmangada** [comment]
Actully I found it by label. Its not yet showing on participating repo. But once you approve PR, this PR it shown on hacktoberfest page.

**Comment by salmangada** [comment]
@hanshulll 
Actully I found it by label. Its not yet showing on participating repo. But this PR is been shown on hacktoberfest page.

**Comment by hanshulll** [comment]
@salmangada 
Can you be more specific by sharing the screenshot here !!

**Comment by salmangada** [comment]
@hanshulll 
I'am just getting this updates on hacktoberfest page,  not whole repository.

image

**Comment by hanshulll** [comment]
@salmangada 
**cool thank you so much for your contribution i will accept it soon and congrats on your PR though you have to put your project in the main directory but it's fine i'll change it own my own**

**Comment by salmangada** [comment]
@hanshulll 
Thank you very much for your guidance.

**Review by hanshulll — APPROVED** [review]

**Comment by hanshulll** [comment]
@salmangada 
**Your PR has been merged do-follow and give a star to the repository**

**Comment by salmangada** [comment]
@hanshulll 
Thankyou

**Pull request merged**
