### PR TITLE
made a city website using html,css

### PR DESCRIPTION
**Pull request by YOGENDERSS**

### CODE REVIEW

**Review by hanshulll — APPROVED** [review]
if possible do add some images of your website. I will be merging it in few minutes.

**Comment by hanshulll** [comment]
@YOGENDERSS 
**do follow and star the repositories and check Hacktoberfest2021 Repository for more contributions**

**Comment by YOGENDERSS** [comment]
i am addiding some pics of the website also

**Comment by hanshulll** [comment]
@YOGENDERSS 
**do follow and star the repo. Your PR is merged keep hacking**

**Pull request merged**
